# Generated by Django 5.1.5 on 2026-08-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharterInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(editable=False, max_length=30, unique=True)),
                ('trip_type', models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip'), ('multi_city', 'Multi-City'), ('empty_leg', 'Empty Leg')], default='one_way', max_length=20)),
                ('departure_city', models.CharField(max_length=150)),
                ('arrival_city', models.CharField(max_length=150)),
                ('departure_date', models.CharField(max_length=50)),
                ('departure_time', models.CharField(blank=True, default='Flexible / Any Time', max_length=50)),
                ('return_date', models.CharField(blank=True, max_length=50, null=True)),
                ('passenger_count', models.IntegerField(default=4)),
                ('preferred_category', models.CharField(blank=True, default='Ultra Long Range', max_length=100)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=60)),
                ('catering_preferences', models.CharField(blank=True, max_length=255)),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New Inquiry'), ('contacted', 'Contacted / Sourcing'), ('confirmed', 'Booked & Confirmed'), ('archived', 'Archived')], default='new', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Charter Inquiry',
                'verbose_name_plural': 'Charter Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('airport_code', models.CharField(help_text='e.g. DXB / OMDB', max_length=20)),
                ('fbo_terminal', models.CharField(help_text='e.g. Jetex Executive Lounge', max_length=150)),
                ('region', models.CharField(choices=[('middle_east', 'Middle East'), ('europe', 'Europe'), ('americas', 'Americas'), ('asia_pacific', 'Asia Pacific'), ('caribbean_islands', 'Exotic & Islands')], default='europe', max_length=40)),
                ('tagline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
                ('flight_time_london', models.CharField(default='6h 45m', max_length=50)),
                ('flight_time_ny', models.CharField(default='12h 30m', max_length=50)),
                ('featured', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmptyLegDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_city', models.CharField(max_length=100)),
                ('origin_code', models.CharField(max_length=20)),
                ('destination_city', models.CharField(max_length=100)),
                ('destination_code', models.CharField(max_length=20)),
                ('departure_date', models.CharField(max_length=60)),
                ('aircraft_name', models.CharField(max_length=120)),
                ('aircraft_category', models.CharField(max_length=60)),
                ('passenger_capacity', models.IntegerField(default=12)),
                ('regular_price_usd', models.IntegerField()),
                ('empty_leg_price_usd', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Under Inquiry'), ('booked', 'Booked')], default='available', max_length=20)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FleetAircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('manufacturer', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('light', 'Light Jet'), ('midsize', 'Midsize Jet'), ('super_midsize', 'Super Midsize Jet'), ('heavy', 'Heavy Jet'), ('ultra_long_range', 'Ultra Long Range')], default='ultra_long_range', max_length=40)),
                ('tagline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('range_nm', models.IntegerField(help_text='Nautical Miles (nm)')),
                ('speed_mach', models.DecimalField(decimal_places=2, help_text='e.g. 0.90', max_digits=4)),
                ('max_passengers', models.IntegerField()),
                ('cabin_height', models.CharField(default='6 ft 2 in', max_length=50)),
                ('cabin_width', models.CharField(default='8 ft 0 in', max_length=50)),
                ('cabin_length', models.CharField(default='54 ft', max_length=50)),
                ('baggage_cu_ft', models.IntegerField(default=195, help_text='Cubic feet')),
                ('hourly_rate_usd', models.IntegerField(default=12000)),
                ('exterior_image', models.URLField(max_length=500)),
                ('interior_image', models.URLField(max_length=500)),
                ('amenities', models.TextField(help_text='Newline separated list of luxury cabin amenities')),
                ('featured', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Fleet Aircraft',
                'verbose_name_plural': 'Fleet Aircraft',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MembershipInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=60)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('preferred_tier', models.CharField(max_length=100)),
                ('annual_flight_hours', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membership Inquiry',
                'verbose_name_plural': 'Membership Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_key', models.CharField(choices=[('access', 'Access Tier'), ('prestige', 'Prestige Tier'), ('sovereign', 'Sovereign Tier')], max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=200)),
                ('annual_commitment', models.CharField(max_length=100)),
                ('hourly_rate_info', models.CharField(max_length=150)),
                ('availability_guarantee', models.CharField(default='24 Hours Notice', max_length=100)),
                ('perks', models.TextField(help_text='Newline separated perks')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
