# Generated by Django 5.1.5 on 2026-08-26 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='charterinquiry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charter_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershipinquiry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image_url',
            field=models.URLField(max_length=600),
        ),
        migrations.AlterField(
            model_name='fleetaircraft',
            name='exterior_image',
            field=models.URLField(max_length=600),
        ),
        migrations.AlterField(
            model_name='fleetaircraft',
            name='interior_image',
            field=models.URLField(max_length=600),
        ),
    ]
